batch_size: 1024
clip_gradient_norm: 0.1
clip_targets_to_zero:
- QObs(mm/d)
commit_hash:
data_dir: data/CABra
dataset: cabra
device: cuda:0
dynamic_inputs:
- p_ens
epochs: 1
experiment_name: cabra_qobs
forcings:
- ens
head: regression
hidden_size: 256
initial_forget_bias: 3
learning_rate:
  0: 0.0001
  15: 5e-05
  30: 1e-05
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: NSE
metrics:
- NSE
- KGE
- Alpha-NSE
- Beta-NSE
model: cudalstm
num_workers: 16
number_of_basins: 420
optimizer: AdamW
output_activation: linear
output_dropout: 0.4
package_version: 1.6.0
predict_last_n: 1
save_weights_every: 1
seed: 602800
seq_length: 365
static_attributes:
- clim_p
- clim_pet
- aridity_index
- p_seasonality
- elev_mean
- catch_slope
- catch_area
- sub_porosity
- sub_permeability
- sub_hconduc
- soil_depth
- soil_bulk
- soil_sand
- soil_silt
- soil_clay
- soil_carbon
- catch_wtd
- cover_forest
- cover_grass
target_variables:
- QObs(mm/d)
test_basin_file:  basin_files/test.txt
test_end_date: 31/12/2009
test_start_date: 01/01/2007
train_basin_file: basin_files/train.txt
train_end_date: 31/12/2001
train_start_date: 01/01/1981
validate_every: 1
validate_n_random_basins: 105
validation_basin_file: basin_files/val.txt
validation_end_date: 31/12/2005
validation_start_date: 01/01/2002
